# Files always staged to every worker node regardless of submission type.
# run.sh                      — top-level bash entry point (calls nodescript.sh)
# nodescript.sh               — simulation script generated by generators/bash/
# generators/bash/functions.sh — shared bash functions; arrives on the node as functions.sh
BASE_INPUT_FILES = ["run.sh", "nodescript.sh", "generators/bash/functions.sh"]


def create_file_transfer(scard, extra_input_files=None):
	"""
	Generate the HTCondor file transfer block.

	HTCondor's file transfer mechanism stages input files from the submit
	node to the worker node sandbox before the job starts, and retrieves
	output files after it finishes.

	Type 1 (generator-based) and Type 2 (lund-file-based) use the same
	HTCondor transfer block.  For type-2 jobs, lund files are NOT staged
	here — nodescript.sh fetches each lund file on-node via `pelican object
	get` using the BEARER_TOKEN_FILE injected by the CredMon.  This avoids
	saturating the submit node with large lund directories and is why only
	run.sh and nodescript.sh appear in transfer_input_files.

	transfer_input_files
	    Comma-separated list of files copied TO the worker node.
	    BASE_INPUT_FILES (run.sh, nodescript.sh) are always included.
	    extra_input_files allows callers to append job-specific files
	    (e.g. a custom gcard, bg-merge helper scripts).

	should_transfer_files = YES
	    Unconditionally enable file transfer. The alternative (IF_NEEDED)
	    relies on a shared filesystem between submit and worker nodes, which
	    is not available on the OSG.

	when_to_transfer_output = ON_EXIT
	    Transfer output files back to the submit node when the job exits,
	    regardless of success or failure. ON_EXIT_OR_EVICT would also
	    transfer on eviction but is not needed here because output is
	    written to OSDF via Pelican inside the job.

	transfer_output_files = output
	    Only the 'output/' subdirectory is retrieved. All final hipo files
	    are written there by nodescript.sh. Retrieving only 'output/'
	    avoids pulling back large intermediate scratch files.

	Args:
		scard:             SConfiguration instance. scard.type informs the
		                   comment block but the generated text is identical
		                   for type 1 and type 2 (lund files are fetched
		                   on-node, not staged via HTCondor).
		extra_input_files: list of str, additional files to stage in.
		                   Defaults to empty list.

	Returns:
		str: HTCondor file transfer block.
	"""
	all_input_files = list(BASE_INPUT_FILES)
	if extra_input_files:
		all_input_files.extend(extra_input_files)

	return """# File transfer: stage scripts in, retrieve output/ directory out.
transfer_input_files    = {0}
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = output

""".format(", ".join(all_input_files))
