def create_executable(scard, user_submission_id):
	"""
	Generate the HTCondor executable and logging block.

	Executable
	    The bash script that HTCondor will invoke on each worker node.
	    'run.sh' is the entry-point wrapper generated by the bash generator
	    (see generators/bash/). It sets up the environment and calls the
	    actual simulation script.

	Error / Output / Log
	    Per-job log paths using HTCondor's $(Cluster) and $(Process) macros:
	      $(Cluster)  — the ClusterId shared by all jobs in this submission
	      $(Process)  — the ProcId, unique per subjob (0, 1, 2, …)
	    Files are written under a 'log/' subdirectory on the submit node
	    inside the job's IWD (initial working directory). The directory must
	    exist before submission; it is created by the bash generator.

	    .err — stderr from the job (gemc output, generator stderr)
	    .out — stdout from the job
	    .log — HTCondor accounting: submit, execute, evict, terminate events

	+ProjectName
	    The OSG/XSEDE project name for fair-share accounting. Must be
	    double-quoted in the submit file. Taken from scard.project.
	    Incorrect or missing project names cause submission to be rejected
	    by the JLab OSG connect service.

	Args:
		scard:               SConfiguration instance. Uses scard.project.
		                     The executable block is identical for type-1
		                     and type-2 submissions; run.sh detects the type
		                     by inspecting the arguments it receives.
		user_submission_id:  int, the DB user_submission_id — used to label
		                     the log subdirectory so logs for different
		                     submissions do not collide.

	Returns:
		str: HTCondor executable and logging block.
	"""
	return """# Executable: bash wrapper script staged to the worker node.
Executable = run.sh

# Per-job log files ($(Cluster).$(Process) gives unique names per subjob).
Error  = log/{0}/job.$(Cluster).$(Process).err
Output = log/{0}/job.$(Cluster).$(Process).out
Log    = log/{0}/job.$(Cluster).$(Process).log

# OSG/XSEDE project for fair-share accounting.
+ProjectName = "{1}"

""".format(user_submission_id, scard.project or "CLAS12")
