"""
generate_condor_card.py

Assemble a complete HTCondor submit file for an OSG CLAS12 simulation job
by calling each section generator in order.

Section order matches the conventions expected by condor_submit:
  1. header          — Universe, container image, site ranking
  2. retry_policy    — on_exit_remove / on_exit_hold / periodic_release
  3. requirements    — slot requirements (Singularity, CVMFS, kernel, glidein)
  4. undesired       — excluded sites (+UNDESIRED_Sites)
  5. authentication  — OAuth token for Pelican/OSDF
  6. hardware        — CPUs, memory, disk
  7. executable      — run.sh path, log files, +ProjectName
  8. file_transfer   — input staging and output retrieval
  9. queue           — Arguments and Queue N  (must be last)
"""

from generators.condor.create_header        import create_header
from generators.condor.create_retry_policy  import create_retry_policy
from generators.condor.create_requirements  import create_requirements
from generators.condor.create_undesired     import create_undesired
from generators.condor.create_authentication import create_authentication
from generators.condor.create_hardware      import create_hardware
from generators.condor.create_executable    import create_executable
from generators.condor.create_file_transfer import create_file_transfer
from generators.condor.create_queue         import create_queue
from generators.lund_helper                 import write_lund_files, LUND_FILES


def generate_condor_card(scard, user_submission_id, extra_input_files=None,
                         undesired_sites=None, target_site=None,
                         cpus=None, memory=None, disk=None, test=False, devel=False):
	"""
	Build and return the full HTCondor submit file as a single string.

	Each section is generated by a dedicated function in generators/condor/.
	Override parameters allow per-submission customisation without modifying
	the generators.

	Args:
		scard:               SConfiguration instance populated from the DB scard.
		user_submission_id:  int, DB user_submission_id for this batch.
		extra_input_files:   list of str, additional files to stage to the node.
		undesired_sites:     list of str, site names to exclude. None → defaults.
		target_site:         str, GLIDEIN_Site name to pin all jobs to one site
		                     (e.g. "CNAF"). None means no site restriction.
		cpus:                int, CPU cores per slot. None → default (1).
		memory:              str, memory per slot. None → default ("2.256 GB").
		disk:                str, scratch disk per slot. None → default ("2 GB").
		test:                bool, enable fallbacks for missing dependencies
		                     (pelican mockup). Default False — missing deps fail.
		devel:               bool, use the devel singularity image. Default False.

	Returns:
		str: complete HTCondor submit file content.
	"""
	all_input_files = list(extra_input_files) if extra_input_files else []
	if scard.bkmerging:
		all_input_files.append("bg_merge_bk_file.sh")
	if scard.type == '2':
		write_lund_files(scard.generator, test=test)

	sections = [
		create_header(scard, devel=devel),
		create_retry_policy(scard),
		create_requirements(scard, target_site=target_site),
		create_undesired(scard, undesired_sites=undesired_sites),
		create_authentication(scard),
		create_hardware(scard, cpus=cpus, memory=memory, disk=disk),
		create_executable(scard, user_submission_id),
		create_file_transfer(scard, extra_input_files=all_input_files or None),
		create_queue(scard, user_submission_id),
	]
	return "".join(sections)
